### ISSUE TITLE
Engineering means designing and building real mechanical systems, like vehicular engines and turbojets, aeronautical vehicles, etc. 

### ISSUE THREAD

**Issue by ghost** [heavyelement/ail#5]
This post is related to numerous false claims you make against Engineering in some of your videos.
Hey @heavyelement Gardiner, 

please stop making false claims about real Engineering. There is no such thing as "software" "engineering". That is most disrespectful lie ever. Valve and microsoft have no engineers, nor are they even close to know anything about engineering. They (and all other software clown losers) are nothing but worthless & stupid loser software kiddos. Please stop being disrespectful to real engineering (mechanical engineering is the ONLY engineering). Engineering is a real subject. Engineering means designing and building real mechanical systems, like vehicular engines and turbojets, aeronautical vehicles, etc. Engineering has nothing to do with sitting behind keyboard and writing code. Software dev is easy and has absolutely nothing to do with engineering. Engineering is a complex and deep subject. But software devs these days are being silly wannabe's when they start to talk about this great subject.

Death to "univeristies" [dumpsterversities]. Death to open source.

Mechanical Engineering is the ONLY engineering. Period.

Cheers

**Comment by heavyelement** [comment]
What a loser. Guy deleted his account. The original username was MekanikalEnjy and he deleted his account after spamming my repos. Get rekt, loser.
